services:
  mongo:
    image: mongo:7
    container_name: mongo
    command: ["mongod", "--config", "/etc/mongod.conf"]
    volumes:
      - ./mongodb_config/mongod.conf:/etc/mongod.conf:ro
      - ./mongodb_config/data:/data/db
      - ./mongodb_config/logs:/var/log/mongodb
    ports:
      - "27017:27017"


  redis:
    image: redis:7
    container_name: chatapp-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 10

  api:
    build:
      context: .            # <— Dockerfile nằm ngay thư mục này
      dockerfile: Dockerfile
    container_name: chatapp-api
    env_file: .env
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://mongo:27017/chatapp?directConnection=true
      - REDIS_URL=redis://redis:6379
    ports:
      - "3000:3000"         # host:container
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: ["pnpm","start:dev"]

volumes:
  mongo_data:
